"""Where uploaded and generated files live.

The MVP stores everything on local disk, but every caller goes through
:class:`ArtifactStore` rather than building paths itself. That buys two things:

*One place to change.* Adding S3 or GCS later means writing a second
implementation, not auditing the codebase for ``os.path.join``.

*One place to enforce containment.* Every path handed back out is checked to
be inside the storage root, so a task id or artifact name that has been
tampered with cannot reach a file elsewhere on the machine -- even though the
API also restricts downloads to paths a run actually recorded. The two checks
are independent on purpose; neither relies on the other being correct.
"""

from __future__ import annotations

import os
import re
import shutil
import uuid
from abc import ABC, abstractmethod

from app.config.settings import Settings, get_settings

#: A task id is generated by the server, but it is also accepted from the URL
#: on retrieval, so it is constrained before it is ever used as a path segment.
SAFE_SEGMENT = re.compile(r"^[A-Za-z0-9_-]{1,64}$")


class StorageError(Exception):
    """A storage operation could not be completed safely."""


class ArtifactStore(ABC):
    """The storage contract the rest of the backend depends on."""

    @abstractmethod
    def upload_directory(self, task_id: str) -> str:
        """Return the directory holding the inputs of ``task_id``."""

    @abstractmethod
    def output_directory(self, task_id: str) -> str:
        """Return the directory tool artifacts for ``task_id`` are written to."""

    @abstractmethod
    def write_upload(self, task_id: str, content: bytes, extension: str) -> str:
        """Persist one uploaded file and return its location."""

    @abstractmethod
    def exists(self, reference: str) -> bool:
        """Return whether ``reference`` still resolves to a stored object."""

    @abstractmethod
    def size(self, reference: str) -> int:
        """Return the size of a stored object in bytes."""

    @abstractmethod
    def delete_task(self, task_id: str) -> None:
        """Remove everything stored for one task."""


class LocalArtifactStore(ArtifactStore):
    """Filesystem-backed storage rooted at ``settings.storage_root``."""

    def __init__(self, settings: Settings | None = None) -> None:
        #: Left unset by default so the store follows the live configuration.
        #: Binding settings at construction would pin the storage root for the
        #: life of the process, which breaks per-test isolation and any
        #: reconfiguration at runtime.
        self._settings = settings

    @property
    def settings(self) -> Settings:
        return self._settings or get_settings()

    # -- roots --------------------------------------------------------
    @property
    def root(self) -> str:
        return os.path.abspath(self.settings.storage_root)

    def _segment(self, task_id: str) -> str:
        """Validate a task id before it becomes part of a path."""
        if not SAFE_SEGMENT.match(task_id or ""):
            raise StorageError(
                f"'{task_id}' is not a usable task identifier. Task ids may "
                "contain letters, digits, underscores and hyphens only."
            )
        return task_id

    def _directory(self, kind: str, task_id: str) -> str:
        path = os.path.join(self.root, kind, self._segment(task_id))
        os.makedirs(path, exist_ok=True)
        return self.resolve(path)

    def upload_directory(self, task_id: str) -> str:
        return self._directory("uploads", task_id)

    def output_directory(self, task_id: str) -> str:
        return self._directory("outputs", task_id)

    # -- containment --------------------------------------------------
    def resolve(self, reference: str) -> str:
        """Return the absolute path of ``reference``, or refuse to leave the root.

        ``os.path.realpath`` is used rather than ``abspath`` so a symlink
        pointing outside the storage root is caught as well as a ``..``.
        """
        candidate = os.path.realpath(os.path.abspath(reference))
        root = os.path.realpath(self.root)
        if candidate != root and not candidate.startswith(root + os.sep):
            raise StorageError(
                "Refusing to access a path outside the configured storage root."
            )
        return candidate

    def contains(self, reference: str) -> bool:
        """Return whether ``reference`` lies inside the storage root."""
        try:
            self.resolve(reference)
        except StorageError:
            return False
        return True

    # -- objects ------------------------------------------------------
    def write_upload(self, task_id: str, content: bytes, extension: str) -> str:
        """Write ``content`` under a server-generated name.

        The client's filename never becomes part of the path; only the
        validated extension survives, so the stored name is entirely ours.
        """
        suffix = extension if extension.startswith(".") else f".{extension}"
        if not re.match(r"^\.[A-Za-z0-9]{1,10}$", suffix):
            raise StorageError(f"'{extension}' is not a usable file extension.")

        directory = self.upload_directory(task_id)
        path = os.path.join(directory, f"{uuid.uuid4().hex}{suffix}")
        try:
            with open(path, "wb") as handle:
                handle.write(content)
        except OSError as error:
            raise StorageError(f"Could not store the upload: {error}") from error
        return path

    def exists(self, reference: str) -> bool:
        try:
            return os.path.isfile(self.resolve(reference))
        except StorageError:
            return False

    def size(self, reference: str) -> int:
        path = self.resolve(reference)
        try:
            return os.path.getsize(path)
        except OSError as error:
            raise StorageError(f"Could not stat '{reference}': {error}") from error

    def delete_task(self, task_id: str) -> None:
        for kind in ("uploads", "outputs"):
            path = os.path.join(self.root, kind, self._segment(task_id))
            if os.path.isdir(path):
                shutil.rmtree(path, ignore_errors=True)


_store: ArtifactStore | None = None


def get_artifact_store() -> ArtifactStore:
    """Return the process-wide artifact store."""
    global _store
    if _store is None:
        _store = LocalArtifactStore()
    return _store


def reset_artifact_store() -> None:
    """Drop the cached store so the next call re-reads configuration."""
    global _store
    _store = None


__all__ = [
    "ArtifactStore",
    "LocalArtifactStore",
    "StorageError",
    "get_artifact_store",
    "reset_artifact_store",
]
